apiVersion: batch/v1
kind: Job
metadata:
  name: &jobname onsets-and-frames-transcription-2 # this is an arbitrary name for the local container
spec:
  template:
    spec:
      priorityClassName: research-low
      containers:
        - name: *jobname
          image: ls6-stud-registry.informatik.uni-wuerzburg.de/onsets-and-frames-transcription:0.0.1
          imagePullPolicy: "IfNotPresent"
          env:
              - name: DATADIR
                value: "/workspace/data"
              - name: WORKSPACE
                value: "/workspace"
              - name: NUMBA_CACHE_DIR
                value: "/tmp/numba_cache"
          resources:
            limits: &resources
              nvidia.com/gpu: "1"
              cpu: "16"
              memory: "32Gi"
            requests: *resources # sets requests = limits
#           command: ["python3", "onsets-and-frames-pytorch/train.py", "with", "train_on=all", "logdir=runs/02-14-comparing-run", "checkpoint_interval=10000"]
#          command: ["python3", "onsets-and-frames-pytorch/train.py", "with", "train_on=comparing", "logdir=runs/02-14-comparing-run", "checkpoint_interval=10000"]
          command: ["python3", "onsets-and-frames-pytorch/transcribe.py", "models/05-18-frame-model-comparing.pt", "--audio_paths" , "data/inference-dirs-wout-maestro", "--save-path", "predictions", "--onset-threshold=0.4", "--frame-threshold=0.4", "--save-frames=True", "--save-onsets=True"]
          # This command was used for debugging of the pods (infinite sleeping)
          # command: ["/bin/bash", "-c", "--"]
          # args: [ "while true; do sleep 30; done;" ]
          volumeMounts:
              - mountPath: /workspace/data # directory IN the container
                name: &ceph_data data # matches volume-name from below
              - mountPath: /workspace/predictions # directory IN the container
                name: &ceph_predictions predictions # matches volume-name from below
              - mountPath: /workspace/onsets-and-frames-pytorch
                name: &ceph_onsets-and-frames-pytorch onsets-and-frames-pytorch
              - mountPath: /workspace/models
                name: &ceph_models models
              - mountPath: /dev/shm # fixes a common pytorch issue. just always mount this here
                name: dshm
      imagePullSecrets:
        - name: lsx-registry
      restartPolicy: "Never"
      volumes:
          - name: *ceph_data
            cephfs:
                monitors:
                    - 132.187.14.16
                    - 132.187.14.17
                    - 132.187.14.19
                    - 132.187.14.20  # Not important for you, just copy along
                user: extch1  # <namespace>
                path: "/home/ext/ch1/studentMPK/datasets/" # The path you want to mount
                secretRef: # The name of the secret for auth. Is always "ceph-secret"
                  name: ceph-secret
          - name: *ceph_predictions
            cephfs:
                monitors:
                    - 132.187.14.16
                    - 132.187.14.17
                    - 132.187.14.19
                    - 132.187.14.20  # Not important for you, just copy along
                user: extch1  # <namespace>
                path: "/home/ext/ch1/studentMPK/cluster-transcription-2/predictions" # The path you want to mount
                secretRef: # The name of the secret for auth. Is always "ceph-secret"
                    name: ceph-secret
          - name: *ceph_models
            cephfs:
                monitors:
                    - 132.187.14.16
                    - 132.187.14.17
                    - 132.187.14.19
                    - 132.187.14.20  # Not important for you, just copy along
                user: extch1  # <namespace>
                path: "/home/ext/ch1/studentMPK/models/" # The path you want to mount
                secretRef: # The name of the secret for auth. Is always "ceph-secret"
                    name: ceph-secret
          - name: *ceph_onsets-and-frames-pytorch
            cephfs:
                monitors:
                    - 132.187.14.16
                    - 132.187.14.17
                    - 132.187.14.19
                    - 132.187.14.20  # Not important for you, just copy along
                user: extch1  # <namespace>
                path: "/home/ext/ch1/studentMPK/cluster-transcription-2/onsets-and-frames-pytorch" # The path you want to mount
                secretRef: # The name of the secret for auth. Is always "ceph-secret"
                    name: ceph-secret
          - name: dshm # "needs" to be copied along, see above
            emptyDir:
                medium: "Memory"
  backoffLimit: 0
