name: onsets-and-frames-pytorch-miniconda
channels:
  - conda-forge  # necessary because of librosa requirement below (instead of librosa beeing installed via pip)
  - defaults
dependencies:
  - librosa=0.9.2
  - matplotlib
  - mido>=1.2.9 # copied from original jongwook requirement
  - mir_eval>=0.6
  - numpy=1.19.1
  - numpy-base
  - pandas
  - pillow>=6.2.0 # copied from original jongwook requirement
  - pip
  - pretty_midi>=0.2.9
  - python>=3.7.16
  # This upgrade is necessary because the Docker runs with a later pytorch version
  - pytorch>=1.2.0
  # Commented because of strange issues with tensorboard -> solution was downgrade
  # https://stackoverflow.com/questions/70520120/attributeerror-module-setuptools-distutils-has-no-attribute-version
  # - setuptools=65.6.3=py37h06a4308_0
  - setuptools=59.5.0
  - sacred>=0.7.4
  - scikit-learn>=0.23.2
  - scipy>=1.1.0 # copied from original jongwook requirement
  # older tensorboard versions have a weird caching issue where a different amount of iterations is displayed in each run
  - tensorboard>=2.3.0
  - tqdm>=4.28.1 # copied from original jongwook requirement
